/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
#define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
#define _NAMESPACE_CONCAT(NS, ID) NS ## ID
#define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
#define CASADI_PREFIX(ID) DriverlessMPC_CircLineCost_model_1_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#include "DriverlessMPC_CircLineCost/include/DriverlessMPC_CircLineCost.h"

#define PRINTF printf
DriverlessMPC_CircLineCost_float CASADI_PREFIX(sq)(DriverlessMPC_CircLineCost_float x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

DriverlessMPC_CircLineCost_float CASADI_PREFIX(sign)(DriverlessMPC_CircLineCost_float x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

static const solver_int32_default CASADI_PREFIX(s0)[] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
#define s0 CASADI_PREFIX(s0)
static const solver_int32_default CASADI_PREFIX(s1)[] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
#define s1 CASADI_PREFIX(s1)
static const solver_int32_default CASADI_PREFIX(s2)[] = {1, 1, 0, 1, 0};
#define s2 CASADI_PREFIX(s2)
static const solver_int32_default CASADI_PREFIX(s3)[] = {1, 6, 0, 1, 2, 3, 4, 5, 5, 0, 0, 0, 0, 0};
#define s3 CASADI_PREFIX(s3)
static const solver_int32_default CASADI_PREFIX(s4)[] = {4, 1, 0, 4, 0, 1, 2, 3};
#define s4 CASADI_PREFIX(s4)
static const solver_int32_default CASADI_PREFIX(s5)[] = {4, 6, 0, 4, 7, 8, 9, 13, 16, 0, 1, 2, 3, 0, 1, 3, 0, 1, 0, 1, 2, 3, 0, 1, 3};
#define s5 CASADI_PREFIX(s5)
/* evaluate_stages */
solver_int32_default DriverlessMPC_CircLineCost_model_1(const DriverlessMPC_CircLineCost_float **arg, DriverlessMPC_CircLineCost_float **res) 
{
    DriverlessMPC_CircLineCost_float a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20,a21,a22,a23,a24,a25,a26,a27,a28,a29,a30,a31,a32,a33,a34,a35,a36,a37,a38;
    a0=arg[0] ? arg[0][0] : 0;
    a1=sq(a0);
    a2=1.0000000000000000e-02;
    a1=(a2*a1);
    a3=arg[0] ? arg[0][4] : 0;
    a1=(a1-a3);
    a4=arg[0] ? arg[0][1] : 0;
    a5=sq(a4);
    a1=(a1+a5);
    a5=arg[0] ? arg[0][2] : 0;
    a6=arg[1] ? arg[1][0] : 0;
    a7=(a5-a6);
    a8=sq(a7);
    a9=arg[0] ? arg[0][3] : 0;
    a10=arg[1] ? arg[1][1] : 0;
    a11=(a9-a10);
    a12=sq(a11);
    a8=(a8+a12);
    a8=sqrt(a8);
    a12=arg[1] ? arg[1][2] : 0;
    a13=(a8-a12);
    a14=fabs(a13);
    a15=arg[1] ? arg[1][4] : 0;
    a14=(a15*a14);
    a1=(a1+a14);
    a14=1.;
    a16=(a14-a15);
    a17=(a6*a5);
    a18=(a10*a9);
    a17=(a17-a18);
    a17=(a17+a12);
    a12=fabs(a17);
    a18=arg[1] ? arg[1][3] : 0;
    a12=(a18*a12);
    a12=(a16*a12);
    a1=(a1+a12);
    if (res[0]!=0) res[0][0]=a1;
    a1=(a0+a0);
    a2=(a2*a1);
    if (res[1]!=0) res[1][0]=a2;
    a2=(a4+a4);
    if (res[1]!=0) res[1][1]=a2;
    a18=(a18*a16);
    a17=sign(a17);
    a17=(a17*a18);
    a6=(a6*a17);
    a7=(a7+a7);
    a13=sign(a13);
    a13=(a13*a15);
    a8=(a8+a8);
    a13=(a13/a8);
    a7=(a7*a13);
    a6=(a6+a7);
    if (res[1]!=0) res[1][2]=a6;
    a11=(a11+a11);
    a11=(a11*a13);
    a10=(a10*a17);
    a11=(a11-a10);
    if (res[1]!=0) res[1][3]=a11;
    a11=-1.;
    if (res[1]!=0) res[1][4]=a11;
    a11=arg[0] ? arg[0][5] : 0;
    a10=cos(a11);
    a17=(a3*a10);
    a13=2.5000000000000001e-02;
    a6=(a13*a0);
    a6=(a3+a6);
    a7=1.5300000000000000e+00;
    a8=(a3/a7);
    a15=tan(a4);
    a18=(a8*a15);
    a16=(a13*a18);
    a16=(a11+a16);
    a2=cos(a16);
    a1=(a6*a2);
    a12=2.;
    a1=(a12*a1);
    a17=(a17+a1);
    a1=(a13*a0);
    a1=(a3+a1);
    a19=(a6/a7);
    a20=tan(a4);
    a21=(a19*a20);
    a22=(a13*a21);
    a22=(a11+a22);
    a23=cos(a22);
    a24=(a1*a23);
    a24=(a12*a24);
    a17=(a17+a24);
    a24=5.0000000000000003e-02;
    a25=(a24*a0);
    a25=(a3+a25);
    a26=(a1/a7);
    a27=tan(a4);
    a28=(a26*a27);
    a29=(a24*a28);
    a29=(a11+a29);
    a30=cos(a29);
    a31=(a25*a30);
    a17=(a17+a31);
    a31=8.3333333333333332e-03;
    a17=(a31*a17);
    a5=(a5+a17);
    if (res[2]!=0) res[2][0]=a5;
    a5=sin(a11);
    a17=(a3*a5);
    a32=sin(a16);
    a33=(a6*a32);
    a33=(a12*a33);
    a17=(a17+a33);
    a33=sin(a22);
    a34=(a1*a33);
    a34=(a12*a34);
    a17=(a17+a34);
    a34=sin(a29);
    a35=(a25*a34);
    a17=(a17+a35);
    a17=(a31*a17);
    a9=(a9+a17);
    if (res[2]!=0) res[2][1]=a9;
    a9=(a12*a0);
    a9=(a0+a9);
    a17=(a12*a0);
    a9=(a9+a17);
    a9=(a9+a0);
    a9=(a31*a9);
    a9=(a3+a9);
    if (res[2]!=0) res[2][2]=a9;
    a21=(a12*a21);
    a18=(a18+a21);
    a28=(a12*a28);
    a18=(a18+a28);
    a7=(a25/a7);
    a28=tan(a4);
    a21=(a7*a28);
    a18=(a18+a21);
    a18=(a31*a18);
    a18=(a11+a18);
    if (res[2]!=0) res[2][3]=a18;
    a18=(a13*a2);
    a18=(a12*a18);
    a21=(a13*a23);
    a9=1.6339869281045753e-02;
    a0=(a9*a20);
    a17=(a13*a0);
    a35=sin(a22);
    a36=(a35*a17);
    a36=(a1*a36);
    a21=(a21-a36);
    a21=(a12*a21);
    a18=(a18+a21);
    a21=(a24*a30);
    a9=(a9*a27);
    a36=(a24*a9);
    a37=sin(a29);
    a38=(a37*a36);
    a38=(a25*a38);
    a21=(a21-a38);
    a18=(a18+a21);
    a18=(a31*a18);
    if (res[3]!=0) res[3][0]=a18;
    a18=(a13*a32);
    a18=(a12*a18);
    a21=(a13*a33);
    a22=cos(a22);
    a17=(a22*a17);
    a17=(a1*a17);
    a21=(a21+a17);
    a21=(a12*a21);
    a18=(a18+a21);
    a21=(a24*a34);
    a29=cos(a29);
    a36=(a29*a36);
    a36=(a25*a36);
    a21=(a21+a36);
    a18=(a18+a21);
    a18=(a31*a18);
    if (res[3]!=0) res[3][1]=a18;
    if (res[3]!=0) res[3][2]=a24;
    a0=(a12*a0);
    a9=(a12*a9);
    a0=(a0+a9);
    a9=3.2679738562091505e-02;
    a9=(a9*a28);
    a0=(a0+a9);
    a0=(a31*a0);
    if (res[3]!=0) res[3][3]=a0;
    a0=cos(a4);
    a0=sq(a0);
    a8=(a8/a0);
    a0=(a13*a8);
    a9=sin(a16);
    a18=(a9*a0);
    a18=(a6*a18);
    a18=(a12*a18);
    a21=cos(a4);
    a21=sq(a21);
    a19=(a19/a21);
    a21=(a13*a19);
    a36=(a35*a21);
    a36=(a1*a36);
    a36=(a12*a36);
    a18=(a18+a36);
    a36=cos(a4);
    a36=sq(a36);
    a26=(a26/a36);
    a36=(a24*a26);
    a17=(a37*a36);
    a17=(a25*a17);
    a18=(a18+a17);
    a18=(a31*a18);
    a18=(-a18);
    if (res[3]!=0) res[3][4]=a18;
    a16=cos(a16);
    a0=(a16*a0);
    a0=(a6*a0);
    a0=(a12*a0);
    a21=(a22*a21);
    a21=(a1*a21);
    a21=(a12*a21);
    a0=(a0+a21);
    a36=(a29*a36);
    a36=(a25*a36);
    a0=(a0+a36);
    a0=(a31*a0);
    if (res[3]!=0) res[3][5]=a0;
    a19=(a12*a19);
    a8=(a8+a19);
    a26=(a12*a26);
    a8=(a8+a26);
    a4=cos(a4);
    a4=sq(a4);
    a7=(a7/a4);
    a8=(a8+a7);
    a8=(a31*a8);
    if (res[3]!=0) res[3][6]=a8;
    if (res[3]!=0) res[3][7]=a14;
    if (res[3]!=0) res[3][8]=a14;
    a8=6.5359477124183007e-01;
    a15=(a8*a15);
    a7=(a13*a15);
    a4=(a9*a7);
    a4=(a6*a4);
    a2=(a2-a4);
    a2=(a12*a2);
    a10=(a10+a2);
    a20=(a8*a20);
    a13=(a13*a20);
    a2=(a35*a13);
    a2=(a1*a2);
    a23=(a23-a2);
    a23=(a12*a23);
    a10=(a10+a23);
    a27=(a8*a27);
    a24=(a24*a27);
    a23=(a37*a24);
    a23=(a25*a23);
    a30=(a30-a23);
    a10=(a10+a30);
    a10=(a31*a10);
    if (res[3]!=0) res[3][9]=a10;
    a7=(a16*a7);
    a7=(a6*a7);
    a32=(a32+a7);
    a32=(a12*a32);
    a5=(a5+a32);
    a13=(a22*a13);
    a13=(a1*a13);
    a33=(a33+a13);
    a33=(a12*a33);
    a5=(a5+a33);
    a24=(a29*a24);
    a24=(a25*a24);
    a34=(a34+a24);
    a5=(a5+a34);
    a5=(a31*a5);
    if (res[3]!=0) res[3][10]=a5;
    if (res[3]!=0) res[3][11]=a14;
    a20=(a12*a20);
    a15=(a15+a20);
    a27=(a12*a27);
    a15=(a15+a27);
    a8=(a8*a28);
    a15=(a15+a8);
    a15=(a31*a15);
    if (res[3]!=0) res[3][12]=a15;
    a15=sin(a11);
    a15=(a3*a15);
    a9=(a6*a9);
    a9=(a12*a9);
    a15=(a15+a9);
    a35=(a1*a35);
    a35=(a12*a35);
    a15=(a15+a35);
    a37=(a25*a37);
    a15=(a15+a37);
    a15=(a31*a15);
    a15=(-a15);
    if (res[3]!=0) res[3][13]=a15;
    a11=cos(a11);
    a3=(a3*a11);
    a6=(a6*a16);
    a6=(a12*a6);
    a3=(a3+a6);
    a1=(a1*a22);
    a12=(a12*a1);
    a3=(a3+a12);
    a25=(a25*a29);
    a3=(a3+a25);
    a31=(a31*a3);
    if (res[3]!=0) res[3][14]=a31;
    if (res[3]!=0) res[3][15]=a14;
    return 0;
}

solver_int32_default DriverlessMPC_CircLineCost_model_1_init(solver_int32_default *f_type, solver_int32_default *n_in, solver_int32_default *n_out, solver_int32_default *sz_arg, solver_int32_default *sz_res) 
{
    *f_type = 1;
    *n_in = 2;
    *n_out = 4;
    *sz_arg = 2;
    *sz_res = 4;
    return 0;
}

solver_int32_default DriverlessMPC_CircLineCost_model_1_sparsity(solver_int32_default i, solver_int32_default *nrow, solver_int32_default *ncol, const solver_int32_default **colind, const solver_int32_default **row) 
{
    const solver_int32_default *s;
    switch (i) 
    {
      case 0:
        s = s0;
        break;
      case 1:
        s = s1;
        break;
      case 2:
        s = s2;
        break;
      case 3:
        s = s3;
        break;
      case 4:
        s = s4;
        break;
      case 5:
        s = s5;
        break;
      default:
        return 1;
    }
    
    *nrow = s[0];
    *ncol = s[1];
    *colind = s + 2;
    *row = s + 2 + (*ncol + 1);
    return 0;
}

solver_int32_default DriverlessMPC_CircLineCost_model_1_work(solver_int32_default *sz_iw, solver_int32_default *sz_w) 
{
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 39;
    return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
