/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
#define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
#define _NAMESPACE_CONCAT(NS, ID) NS ## ID
#define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
#define CASADI_PREFIX(ID) DriverlessMPC_CircLineCost_model_50_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#include "DriverlessMPC_CircLineCost/include/DriverlessMPC_CircLineCost.h"

#define PRINTF printf
DriverlessMPC_CircLineCost_float CASADI_PREFIX(sq)(DriverlessMPC_CircLineCost_float x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

DriverlessMPC_CircLineCost_float CASADI_PREFIX(sign)(DriverlessMPC_CircLineCost_float x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

static const solver_int32_default CASADI_PREFIX(s0)[] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
#define s0 CASADI_PREFIX(s0)
static const solver_int32_default CASADI_PREFIX(s1)[] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
#define s1 CASADI_PREFIX(s1)
static const solver_int32_default CASADI_PREFIX(s2)[] = {1, 1, 0, 1, 0};
#define s2 CASADI_PREFIX(s2)
static const solver_int32_default CASADI_PREFIX(s3)[] = {1, 6, 0, 0, 0, 1, 2, 3, 4, 0, 0, 0, 0};
#define s3 CASADI_PREFIX(s3)
/* evaluate_stages */
solver_int32_default DriverlessMPC_CircLineCost_model_50(const DriverlessMPC_CircLineCost_float **arg, DriverlessMPC_CircLineCost_float **res) 
{
    DriverlessMPC_CircLineCost_float a0,a1,a2,a3,a4,a5,a6,a7;
    a0=arg[0] ? arg[0][4] : 0;
    a1=arg[1] ? arg[1][7] : 0;
    a0=(a0-a1);
    a1=sq(a0);
    a2=2.;
    a1=(a2*a1);
    a3=arg[0] ? arg[0][2] : 0;
    a4=arg[1] ? arg[1][5] : 0;
    a3=(a3-a4);
    a4=sq(a3);
    a5=arg[0] ? arg[0][3] : 0;
    a6=arg[1] ? arg[1][6] : 0;
    a5=(a5-a6);
    a6=sq(a5);
    a4=(a4+a6);
    a4=sqrt(a4);
    a1=(a4+a1);
    a6=arg[0] ? arg[0][5] : 0;
    a7=arg[1] ? arg[1][8] : 0;
    a6=(a6-a7);
    a7=sq(a6);
    a1=(a1+a7);
    if (res[0]!=0) res[0][0]=a1;
    a3=(a3/a4);
    if (res[1]!=0) res[1][0]=a3;
    a5=(a5/a4);
    if (res[1]!=0) res[1][1]=a5;
    a0=(a0+a0);
    a2=(a2*a0);
    if (res[1]!=0) res[1][2]=a2;
    a6=(a6+a6);
    if (res[1]!=0) res[1][3]=a6;
    return 0;
}

solver_int32_default DriverlessMPC_CircLineCost_model_50_init(solver_int32_default *f_type, solver_int32_default *n_in, solver_int32_default *n_out, solver_int32_default *sz_arg, solver_int32_default *sz_res) 
{
    *f_type = 1;
    *n_in = 2;
    *n_out = 2;
    *sz_arg = 2;
    *sz_res = 2;
    return 0;
}

solver_int32_default DriverlessMPC_CircLineCost_model_50_sparsity(solver_int32_default i, solver_int32_default *nrow, solver_int32_default *ncol, const solver_int32_default **colind, const solver_int32_default **row) 
{
    const solver_int32_default *s;
    switch (i) 
    {
      case 0:
        s = s0;
        break;
      case 1:
        s = s1;
        break;
      case 2:
        s = s2;
        break;
      case 3:
        s = s3;
        break;
      default:
        return 1;
    }
    
    *nrow = s[0];
    *ncol = s[1];
    *colind = s + 2;
    *row = s + 2 + (*ncol + 1);
    return 0;
}

solver_int32_default DriverlessMPC_CircLineCost_model_50_work(solver_int32_default *sz_iw, solver_int32_default *sz_w) 
{
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 8;
    return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
